config/routes.rb
Rails.application.routes.draw do

  resources :players

  root 'players#new'

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :name, :email, :username, :points, presence: true
  validates :username, length: { in: 5..20 }, uniqueness: true
  validates :points, numericality: { greater_than_or_equal_to: 0 }
  validates :active, inclusion: { in: %w(true false)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)

    if @player.save
      flash[:notice] = "El jugador se ha creado"
      redirect_to :action => 'new'
    else
      render :action => 'new'
    end
  end

  private

  def player_params
    params.require(:player).permit(:email, :name, :username, :points, :active)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Game</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/players/new.html.erb
<h1>Create player</h1>

<%= form_for :player, url: players_path do |f| %>
  <% if @player.errors.any? %>
    <div id = "error_explanation">
      <h2>
        <%= pluralize(@player.errors.count, "error") %> prohibited this artice from being saved:
      </h2>
      <ul>
        <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% elsif flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>  
  <p>
    <%= f.label :email %> <br>
    <%= f.email_field :email %>
  </p>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :username %> <br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :points %> <br>
    <%= f.number_field :points %>
  </p>
  <p>
    <%= f.label :active %> <br>
    <%= f.check_box :active %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>  